const seatLayout = {
  rows: [
    {
      rowType: "PREMIUM",
      rows: [
        {
          rowLabel: "N",
          seats: [
            { label: "1", type: "PREMIUM", available: false },
            { label: "2", type: "PREMIUM", available: false },
            { label: "3", type: "PREMIUM", available: true },
            { label: "4", type: "PREMIUM", available: true },
            { label: "5", type: "PREMIUM", available: true },
            { label: "6", type: "PREMIUM", available: true },
            { label: "7", type: "PREMIUM", available: true },
            { label: "8", type: "PREMIUM", available: true },
            { label: "9", type: "PREMIUM", available: true },
            { label: "10", type: "PREMIUM", available: false },
            { label: "11", type: "PREMIUM", available: true },
            { label: "12", type: "PREMIUM", available: true },
            { label: "13", type: "PREMIUM", available: true },
            { label: "14", type: "PREMIUM", available: false },
            { label: "15", type: "PREMIUM", available: false },
            { label: "16", type: "PREMIUM", available: false },
            { label: "17", type: "PREMIUM", available: false },
            { label: "18", type: "PREMIUM", available: false },
            { label: "19", type: "PREMIUM", available: false },
            { label: "20", type: "PREMIUM", available: false },
            { label: "21", type: "PREMIUM", available: false },
            { label: "22", type: "PREMIUM", available: true },
            { label: "23", type: "PREMIUM", available: true },
            { label: "24", type: "PREMIUM", available: true },
            { label: "25", type: "PREMIUM", available: true },
          ],
        },
        {
          rowLabel: "M",
          seats: [
            null,
            null,
            { label: "1", type: "PREMIUM", available: false },
            { label: "2", type: "PREMIUM", available: false },
            { label: "3", type: "PREMIUM", available: true },
            { label: "4", type: "PREMIUM", available: true },
            null,
            null,
            { label: "5", type: "PREMIUM", available: true },
            { label: "6", type: "PREMIUM", available: false },
            { label: "7", type: "PREMIUM", available: false },
            { label: "8", type: "PREMIUM", available: false },
            { label: "9", type: "PREMIUM", available: false },
            { label: "10", type: "PREMIUM", available: false },
            { label: "11", type: "PREMIUM", available: true },
            { label: "12", type: "PREMIUM", available: true },
            { label: "13", type: "PREMIUM", available: true },
            { label: "14", type: "PREMIUM", available: true },
            null,
            null,
            null,
            { label: "15", type: "PREMIUM", available: true },
            { label: "16", type: "PREMIUM", available: true },
            { label: "17", type: "PREMIUM", available: true },
            { label: "18", type: "PREMIUM", available: true },
          ],
        },
        {
          rowLabel: "L",
          seats: [
            null,
            null,
            { label: "1", type: "PREMIUM", available: false },
            { label: "2", type: "PREMIUM", available: false },
            { label: "3", type: "PREMIUM", available: true },
            { label: "4", type: "PREMIUM", available: true },
            null,
            null,
            { label: "5", type: "PREMIUM", available: true },
            { label: "6", type: "PREMIUM", available: true },
            { label: "7", type: "PREMIUM", available: true },
            { label: "8", type: "PREMIUM", available: true },
            { label: "9", type: "PREMIUM", available: true },
            { label: "10", type: "PREMIUM", available: true },
            { label: "11", type: "PREMIUM", available: true },
            { label: "12", type: "PREMIUM", available: true },
            { label: "13", type: "PREMIUM", available: true },
            { label: "14", type: "PREMIUM", available: true },
            null,
            null,
            null,
            { label: "15", type: "PREMIUM", available: true },
            { label: "16", type: "PREMIUM", available: true },
            { label: "17", type: "PREMIUM", available: true },
            { label: "18", type: "PREMIUM", available: true },
          ],
        },
        {
          rowLabel: "K",
          seats: [
            null,
            null,
            { label: "1", type: "PREMIUM", available: false },
            { label: "2", type: "PREMIUM", available: false },
            { label: "3", type: "PREMIUM", available: true },
            { label: "4", type: "PREMIUM", available: true },
            null,
            null,
            { label: "5", type: "PREMIUM", available: true },
            { label: "6", type: "PREMIUM", available: true },
            { label: "7", type: "PREMIUM", available: true },
            { label: "8", type: "PREMIUM", available: true },
            { label: "9", type: "PREMIUM", available: true },
            { label: "10", type: "PREMIUM", available: true },
            { label: "11", type: "PREMIUM", available: true },
            { label: "12", type: "PREMIUM", available: true },
            { label: "13", type: "PREMIUM", available: true },
            { label: "14", type: "PREMIUM", available: true },
            null,
            null,
            null,
            { label: "15", type: "PREMIUM", available: true },
            { label: "16", type: "PREMIUM", available: true },
            { label: "17", type: "PREMIUM", available: true },
            { label: "18", type: "PREMIUM", available: true },
          ],
        },
        {
          rowLabel: "J",
          seats: [
            null,
            null,
            { label: "1", type: "PREMIUM", available: false },
            { label: "2", type: "PREMIUM", available: false },
            { label: "3", type: "PREMIUM", available: true },
            { label: "4", type: "PREMIUM", available: true },
            null,
            null,
            { label: "5", type: "PREMIUM", available: true },
            { label: "6", type: "PREMIUM", available: true },
            { label: "7", type: "PREMIUM", available: true },
            { label: "8", type: "PREMIUM", available: true },
            { label: "9", type: "PREMIUM", available: true },
            { label: "10", type: "PREMIUM", available: true },
            { label: "11", type: "PREMIUM", available: true },
            { label: "12", type: "PREMIUM", available: true },
            { label: "13", type: "PREMIUM", available: true },
            { label: "14", type: "PREMIUM", available: true },
            null,
            null,
            null,
            { label: "15", type: "PREMIUM", available: true },
            { label: "16", type: "PREMIUM", available: true },
            { label: "17", type: "PREMIUM", available: true },
            { label: "18", type: "PREMIUM", available: true },
          ],
        },
        {
          rowLabel: "I",
          seats: [
            null,
            null,
            { label: "1", type: "PREMIUM", available: false },
            { label: "2", type: "PREMIUM", available: false },
            { label: "3", type: "PREMIUM", available: true },
            { label: "4", type: "PREMIUM", available: true },
            null,
            null,
            { label: "5", type: "PREMIUM", available: true },
            { label: "6", type: "PREMIUM", available: true },
            { label: "7", type: "PREMIUM", available: true },
            { label: "8", type: "PREMIUM", available: true },
            { label: "9", type: "PREMIUM", available: true },
            { label: "10", type: "PREMIUM", available: true },
            { label: "11", type: "PREMIUM", available: true },
            { label: "12", type: "PREMIUM", available: true },
            { label: "13", type: "PREMIUM", available: true },
            { label: "14", type: "PREMIUM", available: true },
            null,
            null,
            null,
            { label: "15", type: "PREMIUM", available: true },
            { label: "16", type: "PREMIUM", available: true },
            { label: "17", type: "PREMIUM", available: true },
            { label: "18", type: "PREMIUM", available: true },
          ],
        },
      ],
    },
    {
      rowType: "EXECUTIVE",
      rows: [
        {
          rowLabel: "H",
          seats: [
            null,
            null,
            { label: "1", type: "EXECUTIVE", available: false },
            { label: "2", type: "EXECUTIVE", available: false },
            { label: "3", type: "EXECUTIVE", available: true },
            { label: "4", type: "EXECUTIVE", available: true },
            null,
            null,
            { label: "5", type: "EXECUTIVE", available: true },
            { label: "6", type: "EXECUTIVE", available: true },
            { label: "7", type: "EXECUTIVE", available: true },
            { label: "8", type: "EXECUTIVE", available: true },
            { label: "9", type: "EXECUTIVE", available: true },
            { label: "10", type: "EXECUTIVE", available: true },
            { label: "11", type: "EXECUTIVE", available: true },
            { label: "12", type: "EXECUTIVE", available: true },
            { label: "13", type: "EXECUTIVE", available: true },
            { label: "14", type: "EXECUTIVE", available: true },
            null,
            null,
            null,
            { label: "15", type: "EXECUTIVE", available: true },
            { label: "16", type: "EXECUTIVE", available: true },
            { label: "17", type: "EXECUTIVE", available: true },
            { label: "18", type: "EXECUTIVE", available: true },
          ],
        },
        {
          rowLabel: "G",
          seats: [
            null,
            null,
            { label: "1", type: "EXECUTIVE", available: false },
            { label: "2", type: "EXECUTIVE", available: false },
            { label: "3", type: "EXECUTIVE", available: true },
            { label: "4", type: "EXECUTIVE", available: true },
            null,
            null,
            { label: "5", type: "EXECUTIVE", available: true },
            { label: "6", type: "EXECUTIVE", available: true },
            { label: "7", type: "EXECUTIVE", available: true },
            { label: "8", type: "EXECUTIVE", available: true },
            { label: "9", type: "EXECUTIVE", available: true },
            { label: "10", type: "EXECUTIVE", available: true },
            { label: "11", type: "EXECUTIVE", available: true },
            { label: "12", type: "EXECUTIVE", available: true },
            { label: "13", type: "EXECUTIVE", available: true },
            { label: "14", type: "EXECUTIVE", available: true },
            null,
            null,
            null,
            { label: "15", type: "EXECUTIVE", available: true },
            { label: "16", type: "EXECUTIVE", available: true },
            { label: "17", type: "EXECUTIVE", available: true },
            { label: "18", type: "EXECUTIVE", available: true },
          ],
        },
        {
          rowLabel: "F",
          seats: [
            null,
            null,
            null,
            null,
            { label: "1", type: "EXECUTIVE", available: false },
            { label: "2", type: "EXECUTIVE", available: false },
            null,
            null,
            { label: "3", type: "EXECUTIVE", available: true },
            { label: "4", type: "EXECUTIVE", available: true },
            { label: "5", type: "EXECUTIVE", available: true },
            { label: "6", type: "EXECUTIVE", available: true },
            { label: "7", type: "EXECUTIVE", available: true },
            { label: "8", type: "EXECUTIVE", available: true },
            { label: "9", type: "EXECUTIVE", available: true },
            { label: "10", type: "EXECUTIVE", available: true },
            { label: "11", type: "EXECUTIVE", available: true },
            { label: "12", type: "EXECUTIVE", available: true },
            null,
            null,
            null,
            { label: "13", type: "EXECUTIVE", available: true },
            { label: "14", type: "EXECUTIVE", available: true },
            { label: "15", type: "EXECUTIVE", available: true },
            { label: "16", type: "EXECUTIVE", available: true },
          ],
        },
        {
          rowLabel: "E",
          seats: [
            null,
            null,
            null,
            null,
            { label: "1", type: "EXECUTIVE", available: false },
            { label: "2", type: "EXECUTIVE", available: false },
            null,
            null,
            { label: "3", type: "EXECUTIVE", available: true },
            { label: "4", type: "EXECUTIVE", available: true },
            { label: "5", type: "EXECUTIVE", available: true },
            { label: "6", type: "EXECUTIVE", available: true },
            { label: "7", type: "EXECUTIVE", available: true },
            { label: "8", type: "EXECUTIVE", available: true },
            { label: "9", type: "EXECUTIVE", available: true },
            { label: "10", type: "EXECUTIVE", available: true },
            { label: "11", type: "EXECUTIVE", available: true },
            { label: "12", type: "EXECUTIVE", available: true },
            null,
            null,
            null,
            { label: "13", type: "EXECUTIVE", available: true },
            { label: "14", type: "EXECUTIVE", available: true },
            { label: "15", type: "EXECUTIVE", available: true },
            { label: "16", type: "EXECUTIVE", available: true },
          ],
        },
        {
          rowLabel: "D",
          seats: [
            null,
            null,
            null,
            null,
            { label: "1", type: "EXECUTIVE", available: false },
            { label: "2", type: "EXECUTIVE", available: false },
            null,
            null,
            { label: "3", type: "EXECUTIVE", available: true },
            { label: "4", type: "EXECUTIVE", available: true },
            { label: "5", type: "EXECUTIVE", available: true },
            { label: "6", type: "EXECUTIVE", available: true },
            { label: "7", type: "EXECUTIVE", available: true },
            { label: "8", type: "EXECUTIVE", available: true },
            { label: "9", type: "EXECUTIVE", available: true },
            { label: "10", type: "EXECUTIVE", available: true },
            { label: "11", type: "EXECUTIVE", available: true },
            { label: "12", type: "EXECUTIVE", available: true },
            null,
            null,
            null,
            { label: "13", type: "EXECUTIVE", available: true },
            { label: "14", type: "EXECUTIVE", available: true },
            { label: "15", type: "EXECUTIVE", available: true },
            { label: "16", type: "EXECUTIVE", available: true },
          ],
        },
        {
          rowLabel: "C",
          seats: [
            null,
            null,
            null,
            null,
            { label: "1", type: "EXECUTIVE", available: false },
            { label: "2", type: "EXECUTIVE", available: false },
            null,
            null,
            { label: "3", type: "EXECUTIVE", available: true },
            { label: "4", type: "EXECUTIVE", available: true },
            { label: "5", type: "EXECUTIVE", available: true },
            { label: "6", type: "EXECUTIVE", available: true },
            { label: "7", type: "EXECUTIVE", available: true },
            { label: "8", type: "EXECUTIVE", available: true },
            { label: "9", type: "EXECUTIVE", available: true },
            { label: "10", type: "EXECUTIVE", available: true },
            { label: "11", type: "EXECUTIVE", available: true },
            { label: "12", type: "EXECUTIVE", available: true },
            null,
            null,
            null,
            { label: "13", type: "EXECUTIVE", available: true },
            { label: "14", type: "EXECUTIVE", available: true },
            { label: "15", type: "EXECUTIVE", available: true },
            { label: "16", type: "EXECUTIVE", available: true },
          ],
        },
      ],
    },
    {
      rowType: "GOLD",
      rows: [
        {
          rowLabel: "B",
          seats: [
            null,
            null,
            null,
            null,
            { label: "1", type: "GOLD", available: false },
            { label: "2", type: "GOLD", available: false },
            null,
            null,
            { label: "3", type: "GOLD", available: true },
            { label: "4", type: "GOLD", available: true },
            { label: "5", type: "GOLD", available: true },
            { label: "6", type: "GOLD", available: true },
            { label: "7", type: "GOLD", available: true },
            { label: "8", type: "GOLD", available: true },
            { label: "9", type: "GOLD", available: true },
            { label: "10", type: "GOLD", available: true },
            { label: "11", type: "GOLD", available: true },
            { label: "12", type: "GOLD", available: true },
            null,
            null,
            null,
            { label: "13", type: "GOLD", available: true },
            { label: "14", type: "GOLD", available: true },
            { label: "15", type: "GOLD", available: true },
            { label: "16", type: "GOLD", available: true },
          ],
        },
        {
          rowLabel: "A",
          seats: [
            null,
            null,
            null,
            null,
            { label: "1", type: "GOLD", available: false },
            { label: "2", type: "GOLD", available: false },
            null,
            null,
            { label: "3", type: "GOLD", available: true },
            { label: "4", type: "GOLD", available: true },
            { label: "5", type: "GOLD", available: true },
            { label: "6", type: "GOLD", available: true },
            { label: "7", type: "GOLD", available: true },
            { label: "8", type: "GOLD", available: true },
            { label: "9", type: "GOLD", available: true },
            { label: "10", type: "GOLD", available: true },
            { label: "11", type: "GOLD", available: true },
            { label: "12", type: "GOLD", available: true },
            null,
            null,
            null,
            { label: "13", type: "GOLD", available: true },
            { label: "14", type: "GOLD", available: true },
            { label: "15", type: "GOLD", available: true },
            { label: "16", type: "GOLD", available: true },
          ],
        },
      ],
    },
  ],
  pricing: {
    PREMIUM: 400,
    EXECUTIVE: 300,
    GOLD: 200,
  },
};

export default seatLayout;
